export default [{
  "cdTipoMvExt": 85,
  "deTipoMvConsulta": "Recife",
  "deAssunto": "Paulista",
  "area": "Cível",
  "cc1": 0,
  "cc2": 1,
  "cc3": 0,
  "cc4": 0,
  "cc5": 0,
  "ccTotal": 1
},
{
  "cdTipoMvExt": 198,
  "deTipoMvConsulta": "Recife",
  "deAssunto": "Paulista",
  "area": "Cível",
  "cc1": 0,
  "cc2": 0,
  "cc3": 0,
  "cc4": 1,
  "cc5": 0,
  "ccTotal": 1
},
{
  "cdTipoMvExt": 11010,
  "deTipoMvConsulta": "Maceio",
  "deAssunto": "Sergipe",
  "area": "Cível",
  "cc1": 0,
  "cc2": 1,
  "cc3": 0,
  "cc4": 0,
  "cc5": 0,
  "ccTotal": 1
},
{
  "cdTipoMvExt": 50038,
  "deTipoMvConsulta": "Bahia",
  "deAssunto": "Salvador",
  "area": "Cível",
  "cc1": 0,
  "cc2": 0,
  "cc3": 0,
  "cc4": 0,
  "cc5": 1,
  "ccTotal": 1
},
{
  "cdTipoMvExt": 50200,
  "deTipoMvConsulta": "Bahia",
  "deAssunto": "Salvador",
  "area": "Cível",
  "cc1": 0,
  "cc2": 1,
  "cc3": 0,
  "cc4": 0,
  "cc5": 1,
  "ccTotal": 2
}];
